# Generated by Django 5.0.2 on 2024-03-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='franchise',
        ),
        migrations.AddField(
            model_name='category',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise'),
        ),
    ]
