# Generated by Django 5.0.2 on 2024-02-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
    ]
