# Generated by Django 5.0.2 on 2024-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_remove_menu_franchise_category_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='finger_print',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
