# Generated by Django 5.0.2 on 2024-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_remove_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('IN', 'INDOOR'), ('OU', 'OUTDOOR'), ('MZ', 'MEZZANINE')], max_length=50),
        ),
    ]
