# Generated by Django 5.0.2 on 2024-03-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_customer_finger_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='finger_print',
        ),
    ]
