# Generated by Django 5.0.2 on 2024-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_franchise_slug_outlet_slug_alter_table_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_codes'),
        ),
    ]
