# Generated by Django 5.0.2 on 2024-03-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0006_kitchenorderticket_served_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorderticket',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.table'),
        ),
    ]
