# Generated by Django 5.0.2 on 2024-03-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0008_tableorder_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='menu_gifs'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='menu-icons'),
        ),
    ]
