# Generated by Django 5.0.2 on 2024-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0010_alter_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=100, null=True),
        ),
    ]
