# Generated by Django 5.0.2 on 2024-03-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0011_tableorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.customer'),
        ),
    ]
