# Generated by Django 5.0.2 on 2024-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0012_alter_tableorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='is_ready_pay',
            field=models.BooleanField(default=False),
        ),
    ]
