# Generated by Django 5.0.2 on 2024-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(null=True),
        ),
    ]
